@startuml basketball

    class 試合映像 {
        - 試合日
        - ホームチーム
        - アウェイチーム
    }

    class プレーイベント一覧 {
        - List<イベント>
    }

    class イベント {
        - タグ
        + 記録():タグ
    }

    class タグ {
        - 発生タイミング
        - チーム名
        - 選手名
        - プレー
        - エリア
        - 結果
    }

    class 発生タイミング{
        - クォーター
        - 残り時間
        - 映像内タイムスタンプ
    }

    class チーム名 {

    }

    class 選手 {
        - 選手名
    }

    class プレー {
        - カテゴリ
        - 詳細種別
    }

    class カテゴリ {

    }

    class 詳細種別 {

    }

    class エリア {

    }

    class ペイントエリア{

    }

    class アウトサイドエリア {

    }

    class コーナーエリア {

    }

    class 結果 {
        - 成功/失敗
        - 獲得点数
        - 速攻フラグ
        - 相手ミス由来フラグ
    }


    試合映像 --> プレーイベント一覧
    試合映像 --> チーム名
    プレーイベント一覧 --> イベント
    イベント --> タグ
    タグ --> 発生タイミング
    タグ --> チーム名
    タグ --> 選手
    タグ --> プレー
    プレー --> カテゴリ
    プレー --> 詳細種別
    タグ --> エリア
    タグ --> 結果
    エリア <|-- ペイントエリア
    エリア <|-- アウトサイドエリア
    エリア <|-- コーナーエリア

@enduml