@startuml

    class 試合映像 {

    }

    class プレーイベント一覧 {
        - List<イベント>
    }

    class イベント {
        - 発生時点
        - プレー内容
        - カテゴリ
        - タグ
    }

    試合映像 --> プレーイベント一覧
    プレーイベント一覧 --> イベント
    
@enduml