@startuml basketball

    class 試合映像 {
        - 試合日
        - ホームチーム
        - アウェイチーム
        - シーズン
    }

    class シーズン {
        - シーズン名
        - 開始日
        - 終了日
    }

    class プレーイベント一覧 {
        - List<イベント>
    }

    class イベント {
        - タグ
        + 記録():タグ
    }

    class タグ {
        - 発生タイミング
        - チーム名
        - 選手名
        - プレー
        - エリア
        - 結果
    }

    class 発生タイミング{
        - クォーター
        - 残り時間
        - 映像内タイムスタンプ
    }

    class チーム {
        - 正式名称
        - 略称
        - ホームタウン
        - 運営法人名
    }

    class ホームタウン {
        - 都道府県
        - 市町村
    }

    class チーム所属情報 {
        - ディビジョン
        - 所属カンファレンス
    }

    class 選手 {
        - 選手名
    }

    class プレー {
        - カテゴリ
        - 詳細種別
    }

    class エリア {

    }

    class ペイントエリア{

    }

    class アウトサイドエリア {

    }

    class コーナーエリア {

    }

    class 結果 {
        - 成功/失敗
        - 獲得点数
        - 速攻フラグ
        - 相手ミス由来フラグ
    }


    試合映像 --> プレーイベント一覧
    試合映像 --> チーム
    試合映像 --> シーズン
    チーム所属情報 --> シーズン
    チーム所属情報 --> チーム
    チーム --> ホームタウン
    プレーイベント一覧 --> イベント
    イベント --> タグ
    タグ --> 発生タイミング
    タグ --> チーム
    タグ --> 選手
    タグ --> プレー
    タグ --> エリア
    タグ --> 結果
    エリア <|-- ペイントエリア
    エリア <|-- アウトサイドエリア
    エリア <|-- コーナーエリア

    note left of チーム
    ホームタウンはER上は
    チームの属性として保持
    end note

@enduml